version: '3.7'

volumes:
  ? postgres-data

services:
  postgres:
    image: postgres:10-alpine
    healthcheck:
      test: pg_isready --username=${POSTGRES_USER:-default_user} --dbname=${POSTGRES_DB:-default_db}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-default_password}
      POSTGRES_USER: ${POSTGRES_USER:-default_user}
      POSTGRES_DB: ${POSTGRES_DB:-default_db}
    ports:
      - 5432:${POSTGRES_PORT:-5432}
    restart: on-failure

  pgweb:
    image: sosedoff/pgweb:latest
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-default_user}:${POSTGRES_PASSWORD:-default_password}@postgres:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-default_db}?sslmode=disable
    ports:
      - 8081:8081
    restart: on-failure
